# Generated by Django 5.1.7 on 2025-05-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='manager_id',
            field=models.IntegerField(default=None),
        ),
    ]
