# Generated by Django 5.1.7 on 2025-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_projects_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
